User.create!([
  {name: "Babi Melka", photo: "https://randomuser.me/api/portraits/men/3.jpg", bio: "I used to spend hours writing creative copy, but now all I do is tell Rytr what I need and it writes everything for me. It's the ultimate AI content writer, and a must-have tool for bloggers, marketers, & entrepreneurs", posts_counter: nil},
  {name: "Arun Tata", photo: "https://randomuser.me/api/portraits/men/4.jpg", bio: "Condimentum mattis pellentesque id nibh tortor. Massa enim nec dui nunc mattis enim. Faucibus a pellentesque sit amet porttitor. Tortor dignissim convallis aenean et tortor at. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est lorem ipsum dolor sit amet. Massa eget egestas purus viverra accumsan in nisl nisi. Mauris ultrices eros in cursus turpis massa. Malesuada fames ac turpis egestas. Ac turpis egestas sed tempus urna et pharetra pharetra. Tempor nec feugiat nisl pretium fusce id. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Odio morbi quis commodo odio aenean sed adipiscing diam.", posts_counter: nil},
  {name: "Alemayehu Libero", photo: "https://randomuser.me/api/portraits/men/5.jpg", bio: "Condimentum mattis pellentesque id nibh tortor. Massa enim nec dui nunc mattis enim. Faucibus a pellentesque sit amet porttitor. Tortor dignissim convallis aenean et tortor at. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est lorem ipsum dolor sit amet. Massa eget egestas purus viverra accumsan in nisl nisi. Mauris ultrices eros in cursus turpis massa. Malesuada fames ac turpis egestas. Ac turpis egestas sed tempus urna et pharetra pharetra. Tempor nec feugiat nisl pretium fusce id. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Odio morbi quis commodo odio aenean sed adipiscing diam.", posts_counter: nil},
  {name: "Fred Sam", photo: "https://randomuser.me/api/portraits/men/6.jpg", bio: "Condimentum mattis pellentesque id nibh tortor. Massa enim nec dui nunc mattis enim. Faucibus a pellentesque sit amet porttitor. Tortor dignissim convallis aenean et tortor at. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est lorem ipsum dolor sit amet. Massa eget egestas purus viverra accumsan in nisl nisi. Mauris ultrices eros in cursus turpis massa. Malesuada fames ac turpis egestas. Ac turpis egestas sed tempus urna et pharetra pharetra. Tempor nec feugiat nisl pretium fusce id. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Odio morbi quis commodo odio aenean sed adipiscing diam.", posts_counter: nil},
  {name: "Jhon Snow", photo: "https://randomuser.me/api/portraits/men/1.jpg", bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", posts_counter: 5},
  {name: "David Smith", photo: "https://randomuser.me/api/portraits/men/2.jpg", bio: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Diam sit amet nisl suscipit adipiscing. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Augue ut lectus arcu bibendum. At varius vel pharetra vel turpis nunc eget lorem. Tellus elementum sagittis vitae et leo duis ut. Auctor urna nunc id cursus metus aliquam. Metus aliquam eleifend mi in nulla. Risus quis varius quam quisque id diam vel quam. Ut aliquam purus sit amet luctus venenatis lectus. Libero volutpat sed cras ornare arcu dui vivamus arcu felis.", posts_counter: 1}
])

Post.create!([
  {author_id: 1, title: "dolorem eum magni eos aperiam quia", text: "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae", comments_counter: nil, likes_counter: nil},
  {author_id: 2, title: "optio molestias id quia eum", text: "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error", comments_counter: nil, likes_counter: nil},
  {author_id: 1, title: "magnam facilis autem", text: "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas", comments_counter: 1, likes_counter: nil},
  {author_id: 1, title: "dolorem dolore est ipsam", text: "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae", comments_counter: 1, likes_counter: nil},
  {author_id: 1, title: "nesciunt quas odio", text: "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque", comments_counter: 1, likes_counter: nil},
  {author_id: 1, title: "eum et est occaecati", text: "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit", comments_counter: 9, likes_counter: nil}
])

Comment.create!([
  {author_id: 6, text: "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium", post_id: 1},
  {author_id: 4, text: "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et", post_id: 1},
  {author_id: 3, text: "quia molestiae reprehenderit quasi aspernatur\naut expedita occaecati aliquam eveniet laudantium\nomnis quibusdam delectus saepe quia accusamus maiores nam est\ncum et ducimus et vero voluptates excepturi deleniti ratione", post_id: 1},
  {author_id: 3, text: "non et atque\noccaecati deserunt quas accusantium unde odit nobis qui voluptatem\nquia voluptas consequuntur itaque dolor\net qui rerum deleniti ut occaecati", post_id: 1},
  {author_id: 3, text: "harum non quasi et ratione\ntempore iure ex voluptates in ratione\nharum architecto fugit inventore cupiditate\nvoluptates magni quo et", post_id: 1},
  {author_id: 3, text: "doloribus at sed quis culpa deserunt consectetur qui praesentium\naccusamus fugiat dicta\nvoluptatem rerum ut voluptate autem\nvoluptatem repellendus aspernatur dolorem in", post_id: 1},
  {author_id: 4, text: "maiores sed dolores similique labore et inventore et\nquasi temporibus esse sunt id et\neos voluptatem aliquam\naliquid ratione corporis molestiae mollitia quia et magnam dolor", post_id: 1},
  {author_id: 5, text: "ut voluptatem corrupti velit\nad voluptatem maiores\net nisi velit vero accusamus maiores\nvoluptates quia aliquid ullam eaque", post_id: 4},
  {author_id: 3, text: "sapiente assumenda molestiae atque\nadipisci laborum distinctio aperiam et ab ut omnis\net occaecati aspernatur odit sit rem expedita\nquas enim ipsam minus", post_id: 5},
  {author_id: 3, text: "voluptate iusto quis nobis reprehenderit ipsum amet nulla\nquia quas dolores velit et non\naut quia necessitatibus\nnostrum quaerat nulla et accusamus nisi facilis", post_id: 1},
  {author_id: 4, text: "ut dolorum nostrum id quia aut est\nfuga est inventore vel eligendi explicabo quis consectetur\naut occaecati repellat id natus quo est\nut blanditiis quia ut vel ut maiores ea", post_id: 2},
  {author_id: 3, text: "expedita maiores dignissimos facilis\nipsum est rem est fugit velit sequi\neum odio dolores dolor totam\noccaecati ratione eius rem velit", post_id: 1}
])
